GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/15

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Adam",
    "subscriberID": "1007",
    "email": "adam@example.com" 
}

###

DELETE http://localhost:3000/subscribers

###

PATCH http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "New Name"
}